# Generated by Django 3.0.4 on 2020-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersarray',
            name='tz',
            field=models.CharField(default='america/losangles', max_length=30),
        ),
    ]
