# Generated by Django 3.0.4 on 2020-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usersarray_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersarray',
            name='activity_periods',
            field=models.CharField(default='date', max_length=30),
        ),
    ]
