# Generated by Django 3.0.4 on 2020-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usersarray_activity_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersarray',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
